config/routes.rb
Golivesms::Application.routes.draw do
  root :to => "site#index"
  match "/terms-and-conditions" => "site#terms",  :as => "terms"
  match "/privacy-policy" => "site#privacy",  :as => "privacy"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @title = "Welcome"
    @current_controller = self
  end
  
  def terms
    @title = "Terms &amp; Conditions"
  end
  
  def privacy
    @title = "Privacy Policy"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def section_link(name,options)
      if options[:action] == @current_action and options[:controller] == @current_controller
         link_to(name, options, :class => 'nav on')
      else
        link_to(name,options,:class=>"nav")
      end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golivesms</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="description" content="GoLiveSMS - Free to End User Text Messaging. ">
  <meta name="keywords", content="FTEU, Text Messaging, free to end user, mobile, mobile marketing, mobile messaging, sms, sms technology">
</head>
<body>
<%= render 'header' %>
<%= yield %>
<%= render 'footer' %>
</body>
</html>

app/views/site/_footer.erb
<div id="footer">
	<div class="container_12">
		<div class="grid_12">
			<div class="left">&copy; 2011 GoLiveSMS. All Rights Reserved.&nbsp;&nbsp;&nbsp;Contact us at <a href="sales@golivesms.com">sales@golivesms.com</a> or call us toll free at (866) 989-2208</div>
			<div class="right">
				<ul>
					<li><%= link_to 'Home', root_path %></li>
					<li><%= link_to 'Terms & Conditions', terms_path %></li>
					<li><%= link_to 'Privacy Policy', privacy_path %></li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/site/_header.html.erb
<div id="header">
	<div class="container_12">
		<div class="grid_12">
			<div class="left"><a href='/'><img src="/assets/header-logo.jpg"></a></div>
			<div class="right">
				<%=section_link('Home',:controller => 'site', :action => 'index')%>
				<%=section_link('Terms & Conditions',:controller => 'site', :action => 'terms' )%>
				<%= link_to 'Privacy Policy', privacy_path, :class => "nav privacy" %>			
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>

app/views/site/index.html.erb
<div class="home-wide">
	<div class="inner">
		<div class="container_12">
			<div class="grid_8">
				<h2>Use the latest SMS<br>technology to stay in touch with your customers.</h2>
				<p class="sub">Chances are you have a cell phone with you right now. If you're attempting to collect a debt, your customers probably have one too. Letters get thrown away and phone go ignored, but 96% of text messages are read.</p>
				<p class="contact"><a href="mailto:sales@golivesms.com">sales@golivesms.com</a>&nbsp;&nbsp;(866) 989-2208</p>
			</div>
			<div class="grid_4" style="position: relative"><div id="iphone"><img src="/assets//iphone.png"></div></div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="container_12 section about">
	<div class="grid_4">
		<div class="headline">
			<h3>Let's face it, letters and phone calls are expensive and response rates are very low.</h3>
		</div>
		<p><em>GoLiveSMS</em> was created in response to these facts. Together our team has more than four decades of banking and direct marketing experience. We bring that experience to you, enabling you to manage your receivables better, with less expense and more customer response.</p>
		<p>For a fraction of the cost, you can notify your customers immediately that you would like to speak with them. Mobile phone users read their messages the instant they arrive, wherever they are and if you choose, they can respond back to you by text. </p>
	</div>
	<div class="grid_4 row">
		<div class="headline">
			<h3>There is no more efficient method of communication than a text message.</h3>
		</div>
		<p>Once you activate the system, it runs 24/7<br> on your schedule.</p>
				<p>You have 100% control over message<br>content and delivery.</p>
				<p>There is no paper, printing or <br>postage to purchase.</p>
				<p>No operator costs or long distance charges.</p>
				<p>Completely secure FTP data<br>management and transfer.</p>
				<p>Just one flat fee per message.</p>
			</ul>
		</p>
	</div>
	<div class="clear"></div>
</div>